import "./globals.css";
import Navbar from "@/components/navbar"
import { ThemeProvider } from "@/components/theme-provider"

export const metadata = {
  title: "Suggestion.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar/>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
